<a href="https://colab.research.google.com/github/shrutikoshatwar/data-set-operations/blob/main/speacialtask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

from google.colab import files
uploaded = files.upload()

Saving feature_description.csv to feature_description.csv

In [6]:
filepath = "/content/feature_description.csv"
df=pd.read_csv(filepath)

In [7]:
df

,Feature,Type,Units,Stage,Description
0,received_snr_db,float,dB,A/B/C,Received signal-to-noise ratio
1,carrier_frequency_ghz,float,GHz,A/B/C,Carrier frequency of the satellite link
2,elevation_angle_deg,float,degrees,A/B/C,Ground-to-satellite elevation angle
3,slant_range_km,float,km,A/B/C,Slant range distance from ground station to sa...
4,timestamp,datetime,UTC,A/B/C,Simulation timestamp
5,fspl_db,float,dB,A,Free Space Path Loss
6,gaseous_attenuation_db,float,dB,A,Atmospheric gas absorption loss
7,excess_attenuation_db,float,dB,A,Path attenuation beyond FSPL and gaseous losses
8,effective_path_length_km,float,km,A,Effective path length through the rain layer
9,specific_attenuation_db_per_km,float,dB/km,A,Specific attenuation (excess attenuation divid...
10,rain_height_km,float,km,A,Rain height above sea level
11,snr_roll_mean_5min,float,dB,B,Rolling standard mean over 5 minutes
12,snr_roll_std_5min,float,dB,B,Rolling standard deviation over 5 minutes
13,snr_roll_max_5min,float,dB,B,Rolling maximum over 5 minutes
14,snr_roll_min_5min,float,dB,B,Rolling minimum over 5 minutes
15,snr_roll_mean_30min,float,dB,B,Rolling mean over 30 minutes
16,snr_roll_std_30min,float,dB,B,Rolling standard deviation over 30 minutes
17,attenuation_roll_mean,float,dB,B,Rolling excess attenuation mean over 5 minutes
18,attenuation_roll_std,float,dB,B,Rolling excess attenuation standard deviation ...
19,attenuation_delta,float,dB,B,Difference in excess attenuation from previous...
20,snr_delta,float,dB,B,Difference in SNR from previous step
21,frequency_ghz,float,GHz,C,Replicated carrier frequency for cross-frequen...
22,itu_k,float,—,C,ITU-R specific attenuation coefficient k
23,itu_alpha,float,—,C,ITU-R specific attenuation exponent alpha
24,station,string,—,B/C,Ground station name for cross-site validation
25,climate,string,—,B/C,Climate type classification
26,simulation_id,string,—,B/C,Simulation run identifier

In [8]:
df.head()

,Feature,Type,Units,Stage,Description
0,received_snr_db,float,dB,A/B/C,Received signal-to-noise ratio
1,carrier_frequency_ghz,float,GHz,A/B/C,Carrier frequency of the satellite link
2,elevation_angle_deg,float,degrees,A/B/C,Ground-to-satellite elevation angle
3,slant_range_km,float,km,A/B/C,Slant range distance from ground station to sa...
4,timestamp,datetime,UTC,A/B/C,Simulation timestamp

In [9]:
df.tail()

,Feature,Type,Units,Stage,Description
22,itu_k,float,—,C,ITU-R specific attenuation coefficient k
23,itu_alpha,float,—,C,ITU-R specific attenuation exponent alpha
24,station,string,—,B/C,Ground station name for cross-site validation
25,climate,string,—,B/C,Climate type classification
26,simulation_id,string,—,B/C,Simulation run identifier

In [10]:
df.shape

(27, 5)

In [11]:
df.columns

Index(['Feature', 'Type', 'Units', 'Stage', 'Description'], dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Feature      27 non-null     object
 1   Type         27 non-null     object
 2   Units        27 non-null     object
 3   Stage        27 non-null     object
 4   Description  27 non-null     object
dtypes: object(5)
memory usage: 1.2+ KB

In [13]:
df.describe()

                Feature   Type Units Stage                     Description
count                27     27    27    27                              27
unique               27      3     7     5                              27
top     received_snr_db  float    dB     B  Received signal-to-noise ratio
freq                  1     23    14    10                               1

In [15]:
df.dtypes

Feature        object
Type           object
Units          object
Stage          object
Description    object
dtype: object

In [16]:
df.isnull().sum()

Feature        0
Type           0
Units          0
Stage          0
Description    0
dtype: int64

In [21]:
df.nunique()

Feature        27
Type            3
Units           7
Stage           5
Description    27
dtype: int64

In [18]:
df.sample(5)

,Feature,Type,Units,Stage,Description
22,itu_k,float,—,C,ITU-R specific attenuation coefficient k
6,gaseous_attenuation_db,float,dB,A,Atmospheric gas absorption loss
1,carrier_frequency_ghz,float,GHz,A/B/C,Carrier frequency of the satellite link
23,itu_alpha,float,—,C,ITU-R specific attenuation exponent alpha
25,climate,string,—,B/C,Climate type classification

In [20]:
df.value_counts()

Feature                         Type      Units    Stage  Description
attenuation_delta               float     dB       B      Difference in excess attenuation from previous step                           1
attenuation_roll_mean           float     dB       B      Rolling excess attenuation mean over 5 minutes                                1
attenuation_roll_std            float     dB       B      Rolling excess attenuation standard deviation over 5 minutes                  1
carrier_frequency_ghz           float     GHz      A/B/C  Carrier frequency of the satellite link                                       1
climate                         string    —        B/C    Climate type classification                                                   1
effective_path_length_km        float     km       A      Effective path length through the rain layer                                  1
elevation_angle_deg             float     degrees  A/B/C  Ground-to-satellite elevation angle                                           1
excess_attenuation_db           float     dB       A      Path attenuation beyond FSPL and gaseous losses                               1
frequency_ghz                   float     GHz      C      Replicated carrier frequency for cross-frequency models                       1
fspl_db                         float     dB       A      Free Space Path Loss                                                          1
gaseous_attenuation_db          float     dB       A      Atmospheric gas absorption loss                                               1
itu_alpha                       float     —        C      ITU-R specific attenuation exponent alpha                                     1
itu_k                           float     —        C      ITU-R specific attenuation coefficient k                                      1
rain_height_km                  float     km       A      Rain height above sea level                                                   1
received_snr_db                 float     dB       A/B/C  Received signal-to-noise ratio                                                1
simulation_id                   string    —        B/C    Simulation run identifier                                                     1
slant_range_km                  float     km       A/B/C  Slant range distance from ground station to satellite                         1
snr_delta                       float     dB       B      Difference in SNR from previous step                                          1
snr_roll_max_5min               float     dB       B      Rolling maximum over 5 minutes                                                1
snr_roll_mean_30min             float     dB       B      Rolling mean over 30 minutes                                                  1
snr_roll_mean_5min              float     dB       B      Rolling standard mean over 5 minutes                                          1
snr_roll_min_5min               float     dB       B      Rolling minimum over 5 minutes                                                1
snr_roll_std_30min              float     dB       B      Rolling standard deviation over 30 minutes                                    1
snr_roll_std_5min               float     dB       B      Rolling standard deviation over 5 minutes                                     1
specific_attenuation_db_per_km  float     dB/km    A      Specific attenuation (excess attenuation divided by effective path length)    1
station                         string    —        B/C    Ground station name for cross-site validation                                 1
timestamp                       datetime  UTC      A/B/C  Simulation timestamp                                                          1
Name: count, dtype: int64